name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.6
  provider: ^4.1.3
  flutter_spinkit: ^4.1.2+1
  simple_animations: ^2.2.1
  flutter_circular_chart: ^0.1.0
  flutter_rating_bar: ^3.0.1+1
  charts_flutter: ^0.6.0
  url_launcher: ^5.4.11
  mapbox_gl: ^0.0.1

  flutter_map:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Perfil.jpeg
    - assets/Light.jpg
    - assets/Hardcore.jpg
    - assets/exercice-personne-agee.jpg
    - assets/Cloud.png
    - assets/Sol.png
    - assets/Sun.png
    - assets/terra.png
    - assets/comodos/banheiro.png
    - assets/comodos/cozinha.png
    - assets/comodos/quarto.png
    - assets/comodos/sala_de_jantar.png
    - assets/comodos/sala.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
    - family: Expletus
      fonts:
        - asset: fonts/ExpletusSans/ExpletusSans-Bold.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-BoldItalic.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-Italic.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-Medium.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-MediumItalic.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-Regular.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-SemiBold.ttf
        - asset: fonts/ExpletusSans/ExpletusSans-SemiBoldItalic.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-ExtraLightitalic.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: icons/MyFlutterApp.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
